### ISSUE TITLE
Can't use hypens (-) in Title or description of the item

### ISSUE THREAD

**Issue by mrlahaye** [turtlecoin/turtlecoin-merchandise-bot#1]
Using the below listing, you'll get an error that the price is incorrect. The issue is that my Title and description field were using hypen.

Issue is with "XIII-2" String. The same applies using URL with "-" into them.

-Final Fantasy XIII-2 Collector's Edition (PS3)
-I have a collector edition of Final Fantasy XIII-2 for PS3. 
Everything included excepts any code that could have been initially included. Price does not includes shipping.
(Cat not included)
https://imgur.com/a/mY4INHT
-500000 TRTL

**Comment by fipsi03** [comment]
Thanks for telling me.. Working on a fix
